name: testworklara

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: testworklara_app
    container_name: testworklara_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8090:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
